version: 2

models:
  - name: obt_credit_risk
    description: "Tabel master One Big Table untuk dashboard Credit Risk"
    columns:
      - name: application_id
        description: "Primary key / Nomor Struk Transaksi"
        tests:
          - unique
          - not_null

      - name: is_default
        description: "Target variabel. 0 = Lancar, 1 = Macet"
        tests:
          - accepted_values:
              arguments:
                values: [0, 1]
                quote: false