name: Jalankan dbt Otomatis

# 1. ORCHESTRATION & TRIGGER
on:
  push:
    branches:
      - main # (CI/CD) Jalan otomatis setiap ada git push
  schedule:
    # (Orchestration) Jalan otomatis jam 6 pagi WITA setiap hari.
    # Karena server GitHub menggunakan waktu UTC, jam 06:00 WITA = jam 22:00 UTC hari sebelumnya.
    - cron: '0 22 * * *' 

jobs:
  dbt-run-job:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Mengambil Kode dari GitHub
        uses: actions/checkout@v4

      - name: 🐍 Menyiapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Menginstal dbt-bigquery
        run: pip install dbt-bigquery

      - name: 🔐 Autentikasi ke Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 🛠️ Setup profil dbt (Koneksi ke BigQuery)
        run: |
          mkdir -p ~/.dbt
          echo "
          my_first_project:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: oauth
                project: potent-catwalk-484317-n0 
                dataset: dbt_staging
                threads: 4
                location: asia-southeast2
          " > ~/.dbt/profiles.yml

      # 2. CONTINUOUS INTEGRATION (CI)
      - name: 🧪 Jalankan dbt Test
        run: dbt test

      # 3. CONTINUOUS DEPLOYMENT (CD)
      - name: 🚀 Jalankan dbt Run
        run: dbt run